FROM microsoft/dotnet:2.2-sdk-alpine AS build
COPY . .

WORKDIR /templates/service/host/IdentityServerHost
RUN dotnet restore
RUN dotnet ef migrations script -i -o migrations-IdentityServerHost.sql

WORKDIR /templates/service/host/Zool_Works.OrganizationSetupService.Host
RUN dotnet restore
RUN dotnet ef migrations script -i -o migrations-OrganizationSetupService.sql

FROM mcr.microsoft.com/mssql-tools AS final
WORKDIR /src
COPY --from=build /templates/service/host/IdentityServerHost/migrations-IdentityServerHost.sql migrations-IdentityServerHost.sql
COPY --from=build /templates/service/host/Zool_Works.OrganizationSetupService.Host/migrations-OrganizationSetupService.sql migrations-OrganizationSetupService.sql
COPY --from=build /templates/service/database/entrypoint.sh .
RUN /bin/bash -c "sed -i $'s/\r$//' entrypoint.sh"
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]